### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by FredericHeem**

### CODE REVIEW

**Comment by FredericHeem** [comment]
Finally, checkit is lodash 4.x compatible.

**Comment by rhys-vdw** [comment]
Why permit lodash v3?

**Comment by FredericHeem** [comment]
Because an app may still depend on other lib that has lodash 3.x as a dependency.

**Comment by NinjaBanjo** [comment]
3.0 is officially no longer maintained, I think it's reasonable to explicitly pull in 4.* only

**Comment by FredericHeem** [comment]
lodash > 4 is now required.

**Comment by rhys-vdw** [comment]
Awesome. Thanks @federicobond.

**Comment by federicobond** [comment]
Thanks, but credit should go to @FredericHeem! :wink:

**Comment by FredericHeem** [comment]
Any plan to release a new version soon ? including *lodash* 4 and 3 makes my app 10% fatter.

**Pull request merged**
